### ISSUE TITLE
No assertion verifying signal was emitted specific number of times

### ISSUE THREAD

**Issue by LeTristanB** [CodeDarigan/WAT#114]
There is 3 assertions for signals:
`signal_was_emitted`. `signal_was_not_emitted`, `signal_was_emitted_with_arguments`

But there is no way to assert a signal was emitted a specific number of times. This assertion exists in GUT https://github.com/bitwes/Gut/wiki/Methods#-assert_signal_emit_countobject-signal_name

**Comment by CodeDarigan** [comment]
Added in 5643efca4d0e83a79fefff6993109e99503d55e8

Example: 
```
add_user_signal("test")
watch(self, "test")
emit_signal("test")
emit_signal("test")
var emit_count: int = 2
asserts.signal_was_emitted_x_times(self, "test", emit_count, "Emitted 'test' twice")
```

**Comment by LeTristanB** [comment]
Thank you
