### ISSUE TITLE
Repeating the Test for a set amount of times

### ISSUE THREAD

**Issue by lars-hoeck** [CodeDarigan/WAT#115]
It would be nice, if I could run a test like 100 times in a row.

WHY?
Because you could find interdependencies of your test that way.

If your test succeeded 99/100 times, then you probably have an interdependencie

**Comment by CodeDarigan** [comment]
I could repeat tests easily enough. The biggest problem would be with visualizing it. 

I'm thinking, if a repeat toggle is on, then we would run the test x times and besides each test we would have another column (or maybe just a a text bracket) like

( Passed Tests / Times Tested )
( 99 / 100 )

**Comment by CodeDarigan** [comment]
Closing. See #132.

**Comment by CodeDarigan** [comment]
This has been implemented in the GUI via b72e947004efdf29596e0ef6b17f62ba5ce13f60 and the CLI via 2aabdec6b6da1b298cf55d62e865be6c93872f44

It repeats the tests internally and then dumps all of the combined results at once.
