### ISSUE TITLE
Mocks and Spies

### ISSUE THREAD

**Issue by naqvijafar91** [CodeDarigan/WAT#144]
Hi, I choose WAT instead of GUT because of the awesome documentation, but I was not able to find any example for mocks and spies? Do they exist, if yes, then can you please provide an example for that?

**Comment by CodeDarigan** [comment]
This is a part of the documentation I'm still working on but spies do exist.

Traditional Mocks don't exist (the type that call verify() but test doubles do so things like dummy(), spy(), stub() exist). 

You can find an example of methods [in this script I use to test WAT](https://github.com/CodeDarigan/WAT/blob/master/tests/integration/test_double.test.gd)

**Comment by naqvijafar91** [comment]
Thanks for the response, I searched the previous issues and found out some code samples, then looked into the code base and found the double package. You have done an amazing job with this repo.
