### ISSUE TITLE
Godot 3.2.2b4 Produces PopupMenu Error

### ISSUE THREAD

**Issue by paulhocker** [CodeDarigan/WAT#145]
**Version**
v4.2.1 & MASTER

**Description**
Trying the latest Beta 4 release of 3.2.2 produces the following error on startup.

SCRIPT ERROR: _ready: Trying to assign value of type 'PopupMenu' to a variable of type 'MenuButton'.
          At: <built-in>:15

The TEST panel no longer functions correctly because of this error.

To reproduce: Take a working project with Godot 3.2.1 and open it with the new 3.2.2b4

**Note**
This might also be broken with other 3.2.2 releases, although I have not tested those.

**Possible Fix**

GUI.TSCN contains to variables of type MenuButton they are

Menu & ViewMenu

However, the type of the return value from get_popup() is of type PopupMenu

If you can confirm that MASTER branch is for 3.2.x I can make a patch, test it and make a pull request. Otherwise, I can do it on the 4.2.1 branch.

**Comment by CodeDarigan** [comment]
Resolved by 90c2b6c233bf70dd49d826b0ad29a297a06b35cd
