### ISSUE TITLE
Blank.gd should be blank.gd

### ISSUE THREAD

**Issue by Jummit** [CodeDarigan/WAT#19]
https://github.com/CodeDarigan/WAT/blob/a573911ab7692b3d557daf821bd2e2ff4c9188d6/addons/WAT/utils/input_output.gd#L4
This script doesn't exist. `Blank.gd` should be renamed to `blank.gd`.

**Comment by CodeDarigan** [comment]
Should have been fixed by 0d56091 and 3305758
