### ISSUE TITLE
Crash when reloading after test script is renamed

### ISSUE THREAD

**Issue by Jummit** [CodeDarigan/WAT#21]
Godot crashed after I pressed "Run All Tests" after renaming a test script.

**Comment by CodeDarigan** [comment]
I can't reproduce. What name did you change it from and what did you change it too?

There might be a chance this has nothing to do renaming and deals with a possible issue with yields if you quit your tests too early (the yields don't get flushed properly so you end up in an un-synced state)

**Comment by Jummit** [comment]
I have one test in my test folder with a bunch of tests.
I went to the WAT tab and ran all tests. Then I renamed the test in the FileSystem tab and re-ran all tests. After pressing "Run Script" Godot crashed.

**Comment by CodeDarigan** [comment]
Alright so I get the issue with the single script runner. It checks your directory when you click the option button. That's a matter of simple error handling to update/warn. 

Still no closer to solving to run all tests though. That one should be flushed if you wait for your tests to finish each time.

**Comment by CodeDarigan** [comment]
Added a warning system and early exit for single select script in 1b438a
