### ISSUE TITLE
NOT_IN doesn't exist in operators.gd

### ISSUE THREAD

**Issue by Jummit** [CodeDarigan/WAT#22]
I get the error
```
res://addons/WAT/test/expectations.gd:112 - Invalid get index 'NOT_IN' (on base: 'GDScript').
```
because `const NOT_IN = "not in"` is missing:
https://github.com/CodeDarigan/WAT/blob/58fe802fe6f23736a51c6ae118447b0f25f61df9/addons/WAT/constants/operators.gd#L1-L15

**Comment by CodeDarigan** [comment]
Fixed in 8270ec1
