### ISSUE TITLE
Ouput log should be a bottom tab

### ISSUE THREAD

**Issue by Jummit** [CodeDarigan/WAT#25]
The log should be a tab alongside the other logs like the debugger and the game output IMO.

**Comment by CodeDarigan** [comment]
It was originally but I moved it around to clean stuff up internally. I think I'll consider this after I've refactored some other stuff.

**Comment by CodeDarigan** [comment]
So I've been making a number of changes in the name of refactoring and am starting to consider that the output log is for the most part redundant. 

The first issue is that details like executing script/method/passed/failed is just repeating what we already see in results.

The second issue is that one of the most important pieces of information that we were detailing (Yielding) is better served as its own independent label and or is also covered by a generic total timer.

Speaking about time, the third issue is that this output mechanic ended up adding 4 seconds (which is HUGE) onto the tests.

We could likely just use print statements to detail Starting & End of Test Runner + crash data.

**Comment by CodeDarigan** [comment]
Removed output log making this issue redundant.
