### ISSUE TITLE
Plugin Crashes When res://tests Directory Is Missing

### ISSUE THREAD

**Issue by paulhocker** [CodeDarigan/WAT#27]
Problem:

Trying to activate the Plugin without a tests folder in your project results in Godot crashing.

Recreate Problem:

- Create a new Project
- Import the Plugin using GIT (not asset library)
- Activate the Plugin
- You will receive the Error "res://tests missing"
- Godot will Close

Workaround:

- create the folder "tests" in the root of your project
- activate the Plugin

- create

**Comment by CodeDarigan** [comment]
I've been meaning to create a pop up on instantiation (when you load the plugin) that checks for the folder,  if it isn't there, then create it with an optional name you pass in. This should be in the next release at the very least.

**Comment by paulhocker** [comment]
confirmed that this works.

however, I am unable to run any tests using the master branch as godot crashes when the runner starts. 

I am using 3.1.1 on Windows

as I mentioned in my other response, the config/settings need to be out of the addons folder to be useful so that it can be saved as another asset in my project

thanks again for all the work you are doing on this -- its awesome

**Comment by CodeDarigan** [comment]
It seems a bunch of my UI is looking for a folder that may not exist and doesn't handle it well when it doesn't. A simple fix but there is a lot of them. Should probably get it done within the next 2 days.

**Comment by paulhocker** [comment]
ouch! -- good luck

**Comment by CodeDarigan** [comment]
Okay added two return guards to Folder/Script drop down buttons (these were what was causing the pop up on load) and another on the _run method of the TestRunner itself.

Hopefully nothing should crash now.

**Comment by paulhocker** [comment]
confirmed that master branch is no longer crashing -- thanks for that
