### ISSUE TITLE
Change Test Folder

### ISSUE THREAD

**Issue by paulhocker** [CodeDarigan/WAT#28]
Apologies if this exists somewhere but I did not see it, nor did I find on the Wiki.

Please add the ability to specify the root folder for test scripts. I have several project where the tests are located in folders called

  my_project_tests
  another_project_tests

this lets me keep things separated and organized. 

Ideally this would be a modifiable somewhere in the Project Settings.

**Comment by CodeDarigan** [comment]
This exists but it is a bit hidden anyway in here: https://github.com/CodeDarigan/WAT/tree/master/addons/WAT/Settings

You load up the config resource, pass in the test folder path and then overwrite the original config source. I should probably make an quick access point somewhere for it (like a settings button in the runner that
opens the file in the inspector immediately)

There is also an option to include sub-folders (so you could do tests/project_a, tests/project_b). I can't remember if master can do this recursively though using subfolders of subfolders (ie tests/project_a/unit, tests/project_a/integration, tests/project_b/unit, test/project_b/integration)

**Comment by paulhocker** [comment]
I would prefer not to have a tests folder if I can, but if that is the only way I am fine with it too.

Looking at the location of the config.tres I dont see how I can modify that in my project? Well, I guess I can but as soon as I import a new version it will overwrite my changes.

I think Project Settings are the way to go here.  Have it look for something like

WAT/TESTROOT or something like that. 

The UI/Runner would look at these before doing anything.

I guess another option would have the ability to create my own WAT.cfg file where I can put settings for the runner as well. This might come in handy when you add the ability to run headless.

This is a really nice asset you have here. I was drawn to it for the same reasons you created it. I like the idea of running tests in the IDE, not by having to build and run a godot project.

If you are curious why I want to be able to do all this customization, it is because I use a project manager system for my games where I like to keep everything clean and organized. 

https://gitlab.com/godot-stuff/gs-project-manager

Keep up the great work.

**Comment by CodeDarigan** [comment]
> I would prefer not to have a tests folder if I can, but if that is the only way I am fine with it too.

I don't understand what you mean by this? Where do you store your tests if not in a folder? Unless you mean you don't want a folder named tests but something else instead that you point?

> Looking at the location of the config.tres I dont see how I can modify that in my project? Well, I guess I can but as soon as I import a new version it will overwrite my changes.

You mean once you import a new version of WAT the config that exists there will overwrite what you had? I didn't consider this before (because for me they are one and the same).

**Comment by paulhocker** [comment]
> 
> 
> > I would prefer not to have a tests folder if I can, but if that is the only way I am fine with it too.
> 
> I don't understand what you mean by this? Where do you store your tests if not in a folder? Unless you mean you don't want a folder named tests but something else instead that you point?
> 

Correct -- I dont want a folder named "tests" -- as an example one of my project has a test folder called "doa_tests"

> > Looking at the location of the config.tres I dont see how I can modify that in my project? Well, I guess I can but as soon as I import a new version it will overwrite my changes.
> 
> You mean once you import a new version of WAT the config that exists there will overwrite what you had? I didn't consider this before (because for me they are one and the same).

Right, which is why I would suggest you allow developer to add a WAT.tres or WAT.cfg in the res:// folder -- have your process look for that first, and then use the one in the addons as a fallback

**Comment by CodeDarigan** [comment]
You have the ability to rename the main test folder in the settings at the moment (and I'll add it to the prompt that exists when you load the plugin too. 

Do you want multiple top level folders like res://something_tests & res://something_else_tests?

**Comment by paulhocker** [comment]
> 
> 
> You have the ability to rename the main test folder in the settings at the moment (and I'll add it to the prompt that exists when you load the plugin too.

thanks

> 
> Do you want multiple top level folders like res://something_tests & res://something_else_tests?

i think that would be a nice to have, for me as long as I can specify the root and then have it run through all sub folder under that I am good
