### ISSUE TITLE
Autoloads Are Not Recognized When Running Tests

### ISSUE THREAD

**Issue by paulhocker** [CodeDarigan/WAT#32]
I have an Autoload Script that does not appear to be loading before the Tests begin to run. I am trying to create a sample project for you but I thought I would report it anyway first.

I will update this with more information when my sample project is ready for you.

**Comment by paulhocker** [comment]
I looked at the code today and I am not seeing any way to bootstrap an Autoload script. This is kind of a big deal because I have several Autoload's that I use for other Scripts and writing tests over them results in errors because it cannot find the Autoload's.

Is this even possible running the Scripts in the Editor?

Is that why GUT runs them outside of the Editor?

**Comment by paulhocker** [comment]
Thanks, I will try that -- I think you can close this issue then.

**Comment by paulhocker** [comment]
It works great with the Stand Alone Scene. Too bad I cant run it in the Editor -- maybe one day.

**Comment by CodeDarigan** [comment]
Check #44 for possible solution!
