### ISSUE TITLE
Capitalized folders on Linux.

### ISSUE THREAD

**Issue by luizcarlos1405** [CodeDarigan/WAT#33]
I've just downloaded version 3.0 and got an error message while trying to run a test. It turns out that the script runner.gd had at line 7 the following code:

const COLLECT = preload("res://addons/WAT/**runner**/collect.gd")

I had to change it to:
const COLLECT = preload("res://addons/WAT/**Runner**/collect.gd")

Because of Linux. I see that in the newest commit code there is the same problem of capitalized paths.

**Comment by CodeDarigan** [comment]
Late to this. Went through all current scripts and capitalized Runner for now. Hopefully everything is fine now.

**Comment by CodeDarigan** [comment]
I've started using Linux myself so I know this is resolved.
