### ISSUE TITLE
Possible Autoload Solution

### ISSUE THREAD

**Issue by CodeDarigan** [CodeDarigan/WAT#44]
See #32 and #42 for related discussions.

The primary issue with Autoloads is that they don't seem to be instanced during tests (and or on the same tree?) However we seem to be able to call:

`EditorPlugin.new().add_autoload_singleton("AlreadyExistingName", "res://AutoLoad.gd")`

With no issues and it works inside tests? On that note however, "remove_autoload" will take it away from the current test and the entire project too so avoid that.

**Comment by paulhocker** [comment]
I tried adding the code to one of my tests in the start() function, no dice. I will need to play around with this some more. Perhaps if you exposed the editor plugin object to the test I can add it. By itself, instantiating and trying to add it does not work. :(

**Comment by CodeDarigan** [comment]
Solved as of the latest merge into master.

You still use WAT through the editor but when you run the tests, they are now run in the game context automatically meaning you can access autoloads from there!

**Comment by paulhocker** [comment]
gonna try this out thanks -- will this work in 3.1 or is it 3.2 only?

**Comment by CodeDarigan** [comment]
It should work in 3.1 (if you don't use the new TestSuiteOfSuites class anyway).
