### ISSUE TITLE
Offer easy way to hit breakpoints in unit tests

### ISSUE THREAD

**Issue by Boivin92** [CodeDarigan/WAT#56]
**Problem:** Hitting a breakpoint in a unit-test is currently not possible through the WAT interface. 

**Potential solution:** I suggest adding a "Debug selected X" button somewhere in the interface that would launch a godot scene running the selected tests (either script or directory, like the current interface)

This would allow the use of in-built godot breakpoints without the users having to create custom debugging scenes.

**Comment by Boivin92** [comment]
I'll try and prototype a solution

**Comment by CodeDarigan** [comment]
Alright so for the time being, you should be able to add breakpoints and then run WAT as a scene and not an editor tool.

This is obviously not ideal because we don't want users to care about WAT data. To figure this out I need to figure out if there is a straightforward way of running a scene from the editor. We could possibly execute the scene by passing in commandline arguments from Godot, save the results in a resource, then read those resources for results display.

**Comment by CodeDarigan** [comment]
To re-emphasize; Once I figure out how I can click a tool button to make WAT run a scene implicitly, then a lot of this work is done.

**Comment by Boivin92** [comment]
I [asked on the godot Reddit](https://www.reddit.com/r/godot/comments/efwvy0/how_do_you_launch_godot_from_tool_script/) and WillNationsDev pointed me towards the [Os.execute(...)](https://docs.godotengine.org/en/3.1/classes/class_os.html#class-os-method-execute) method

But I don't know if this allows for breakpoints to be hit or if it just runs the engine with a target scene

**Comment by Boivin92** [comment]
Ok so a quick test confirmed me that the debugger isn't linked when you use OS.execute to launch a scene

**Comment by CodeDarigan** [comment]
Yeah that's a problem. I could figure out a slightly convoluted way to pass results from the scene to the editor via resources but no debugger. If this is going to happen, it won't be for a while if at all.

**Comment by CodeDarigan** [comment]
If you pass "-d" for the debugger, you can access a command-line version. You think something like this might suffice for the time being? A Command Line option also means being able to affect tests on servers if you have no visual interface.

![image](https://user-images.githubusercontent.com/47497501/71493285-6d477a00-2835-11ea-907e-02fec1c4cdc4.png)

I'm not able to access breakpoints from toolscripts I think.

**Comment by CodeDarigan** [comment]
To be clear, you can run it via

godot -s -d addons/WAT/CLI.gd -run_? from the command-line.

**Comment by Boivin92** [comment]
We could get around this problem by creating a custom node that does all the boilerplate for us.

Example: 
```
extends Node

class_name TestDebugger

export (GDScript) var testScript : GDScript

func _ready():
	var script = testScript.new()
	if script is WATTest:
		#Test Runner sequence (Start -> Pre -> Test -> etc...)
		pass
```

If we give it a cute icon and some documentation, it makes creating the testing scene really quick and allows to drag & drop the test scripts. Then we simply use good old F6 and our breakpoints are hit.

Not perfect, but better than nothing.

**Comment by CodeDarigan** [comment]
I managed to figure out a way to get it into the button. 
![image](https://user-images.githubusercontent.com/47497501/71499932-ad6d2380-285a-11ea-8a22-b077de99bc2e.png)

Basically we search up the editor tree until we get the editor node (is there an easier way to get this?) and then we can access the _menu_option method, then we passed in an enum value (the enum itself having been copied from here: https://github.com/godotengine/godot/blob/22782d519c263febe0af94c7765fd79565c0f3ce/editor/editor_node.h)

I clicked that test runner button below and voila, we got the current open scene running. More detailed iterations could set the particular scene via your export idea there.

**Comment by CodeDarigan** [comment]
Alright I messed around in the experimental branch. This is feasibly but it touches pretty much the whole code base. I've been planning on a proper refactor/rewrite for a while so this seems to be better set for 5.0 which might be a while. However it will solve this issue, solve the other issue with autoloads and probably handle some-side effect related things. Hopefully without changing the user interface too much.

**Comment by Boivin92** [comment]
Alright, thanks for the info, I'll look forward to 5.0 then :)

**Comment by CodeDarigan** [comment]
Resolved as of the latest merge! You still control WAT from the editor view but when you click the run, the test runner starts in the game context, giving you the ability to debug tests (this is also available to the command line interface).
