### ISSUE TITLE
Master is now at 3.2 status

### ISSUE THREAD

**Issue by CodeDarigan** [CodeDarigan/WAT#58]
I'd imagine since 3.2 shouldn't be a breaking change, that master should just default to it instead of a separate branch. Keeping this here as a reminder.

**Comment by Boivin92** [comment]
Just imported WAT 4.0 Master in a fresh 3.2 Beta 6 project and WAT is not compiling. There might have been a breaking change after all

type_library.gd, line 3, "function signature doesn't match the parent. Parent signature is "String to_string()"

**Comment by CodeDarigan** [comment]
This issue was fixed 27 days ago. 3.2 introduced a to_string method clashing with one I've created but 27 days ago I changed it to this, so you must be using an older version, maybe not using master, or maybe godot has left some of the older versions of WAT behind.

![image](https://user-images.githubusercontent.com/47497501/72441424-91e2a200-37a2-11ea-8953-29b90d650578.png)

**Comment by CodeDarigan** [comment]
I think you're using the 4.0 branch, not the master branch which renamed that method. 4.0 is for Godot 4.0 and isn't up to date yet.

**Comment by Boivin92** [comment]
I simply imported WAT from the asset-lib and assumed it pointed to the master branch. I'll try to manually download and import the right code

**Comment by CodeDarigan** [comment]
Nah. AssetLib is a release-instance situation. One guy reviews it all. Not pushing master there until 3.2 is stable.
