### ISSUE TITLE
Add Generic Creation Method

### ISSUE THREAD

**Issue by CodeDarigan** [CodeDarigan/WAT#61]
Basically sometimes you need to create an object to suit a purpose and that object needs data. We take in the object script/class, read what it needs, populate it, then return it back up to the test so it would read:

var object = _create_junk_object(object.klass)

**Comment by CodeDarigan** [comment]
Probably going to leave this. Basic elements are probably better created with literals and complex objects are probably too complex for this to handle. Possibly more suited to an Inversion Of Control framework in the first place.

**Comment by AlexDarigan** [comment]
Reopening unresolved issue. We could include this as part of the external test double plugin?
