### ISSUE TITLE
filesystem.gd returns paths with two forward slashes between directory and file name

### ISSUE THREAD

**Issue by Grafcube** [CodeDarigan/WAT#63]
### Description
When `filesystem._list` is called, the paths that it returns are like `res://path/to//filename.gd`. This caused a few problems when I tried to load the templates to copy them.

### Possible Fix
In `filesystem.gd` at line 27 -
```typescript
var absolute_path: String = "%s/%s" % [path, name]
```
here, the `/` between the two `%s` could be removed, but when I tried that, `WAT.tscn` kept causing the editor to crash and the error message indicated cyclic reference.
The crashes happened if the addon was enabled, if the scene was opened or if the scene was run (in this case, only the preview window crashed).

**Comment by CodeDarigan** [comment]
Is this causing any issues at the moment or only when you were first trying to do it?

**Comment by Grafcube** [comment]
There aren't any noticeable problems right now. It just causes a hiccup when you try to add/modify anything that uses it. In the case of script templates, I couldn't use `i.path` and instead had to use `script_templates_dir + "/" + i.name`.

**Comment by CodeDarigan** [comment]
This is odd. It seems to show up with one slash when printing the absolute path from line 27 for me.
![Screenshot from 2019-12-28 10-43-07](https://user-images.githubusercontent.com/47497501/71542491-f7d7c880-295e-11ea-859b-3adbe7fd056c.png)

The extra slash might be coming from somewhere else.

**Comment by CodeDarigan** [comment]
(Also to be clear res/user is supposed to be a double slash).

**Comment by CodeDarigan** [comment]
The extra slash you added when you were saving the WATTemplate was redundant since the script_templates directory ends with a forward slash.

**Comment by CodeDarigan** [comment]
Okay. This is actually weird as hell. It shows differently from the print and the slash.

**Comment by CodeDarigan** [comment]
Okay found the issue. You had placed a leading underscore at the wat_templates_dir string. So when you passed that directory to the filesystem.list method, then filesystem was adding an additional slash on top of the one you gave.

**Comment by Grafcube** [comment]
Ah ok. That sort of explains the crash, the scene was looking for a path that didn't exist? I'm not entirely sure.

**Comment by CodeDarigan** [comment]
Yeah the crash was the scene trying to look for testdirectorytestscript rather than testdirectory/testscript
