### ISSUE TITLE
general question

### ISSUE THREAD

**Issue by an7i8** [CodeDarigan/WAT#67]
I am new in game developing. But it's very interesting to know. What is the difference between WAT and Gut? In what moments it's better to use WAT. Why WAT is the best decision for a game testing?)

**Comment by CodeDarigan** [comment]
I think these hold true.

    GUT runs in a scene. WAT runs in the editor itself.

    GUT (last I checked) cannot handle creating Test Doubles that take constructor dependencies (as in it uses the _init method with arguments).

    WAT has parameterized testing (so you can do the same test multiple times only needing to define the different set of arguments per run through).

    WAT has a much larger range of asserts (I think)

    WAT can intentionally crash a test script if one method fails (this isn't documented yet though).

    WAT cleans up after itself with regards to memory. GUT doesn't. (Note: This was largely thanks to the recent method print_stray_nodes builtin to Godot that GUT didn't have during its initial creation).

    GUT allows for inner test classes. WAT doesn't. However WAT has the "context" attribute attached to every asserts call so you can add sub-context to your describe() method context of the parent method.

**Comment by CodeDarigan** [comment]
You may want to ask on https://www.reddit.com/r/godot/ for a better unbiased picture (maybe even more correct).

**Comment by an7i8** [comment]
Thanks
