### ISSUE TITLE
Add "Expand failed tests" button

### ISSUE THREAD

**Issue by Boivin92** [CodeDarigan/WAT#70]
**Problem:** When doing refactoring in code, it's often possible to break multiple tests in multiple parts of the code. Having to manually dig all the failed tests after a full collapse, or having to scroll down to the next failed test, can become a point of friction

**Possible solutions:** 

- A button to quickly collapse all successful tests and expand, down to failure details, all the failed ones. 
- A filtering option to show only a certain category of tests, such as Failing, Passing, potentially later in the lifecycle of WAT things as "Taking longer than X milliseconds" or custom tags on tests, etc...

**Comment by CodeDarigan** [comment]
Throw in bit of a hack in 1c30c4e1734da24778bc9b293e9ae09d05aafa11 to solve this. You'll still see passed details of assertions within methods that have failed but anything that is 100% success will be collapsed.

**Comment by Boivin92** [comment]
Thanks a lot, I'll try this later today
