### ISSUE TITLE
Cannot Run Tests With 4.1

### ISSUE THREAD

**Issue by paulhocker** [CodeDarigan/WAT#71]
Trying to run a very simple test using 3.2RC2 -- Windows 10 -- all default settings -- addons\WAT added to my project.

Very simple test in the res://tests/test.gd 

```
extends WAT.Test

func test_one():
	asserts.is_true(1==1, "should work")

```	
![2020-01-21_19-56-16](https://user-images.githubusercontent.com/2214652/72859037-2f007780-3c88-11ea-8a92-45e1c4c04dc8.png)

**Comment by CodeDarigan** [comment]
Are you using describe("description") at the start of your tests (its mandatory as of now).

**Comment by paulhocker** [comment]
well -- um -- nope -- oops

still -- maybe it could "die" a little nicer?

**Comment by paulhocker** [comment]
confirmed that it works now -- i did not have the description on the test or the title 

i tested it with 3.2 with success -- 3.1 still broken it asks if I want to open the project manager? so i think the other issue should stay open for 3.1 -- sorry
