### ISSUE TITLE
4.1 Does Not Work With Godot 3.1.1

### ISSUE THREAD

**Issue by paulhocker** [CodeDarigan/WAT#73]
Godot 3.1.1 -- Windows 10 -- Empty project with one test

Test Folder:

res://tests

Cannot see any test folders or scripts.

![image](https://user-images.githubusercontent.com/2214652/72859580-fe214200-3c89-11ea-9ca7-5d14152aca60.png)

Errors in the output window

![image](https://user-images.githubusercontent.com/2214652/72859594-0ed1b800-3c8a-11ea-8a9c-859ab214875c.png)

PoolStringArray is using a new 3.2 API "empty" so I do not think that this will work with 3.1 projects

**Comment by CodeDarigan** [comment]
Will spend some time on this use Engine.get_version_info to handle some severe cases.

**Comment by paulhocker** [comment]
gotcha

**Comment by CodeDarigan** [comment]
The Project Manager thing you mentioned in the other issue is that I'm using an enumerated value to run the scene behind the scenes. It seems this value changed from 3.1 to 3.2. Should be a simple if statement to fix

**Comment by CodeDarigan** [comment]
Okay so everything should be working now (or warn that it doesn't work in 3.1)

The only thing I have an issue with is one of my own tests of the testrunner and that's because of a shared resource issue in Godot 3.1 with arrays. It shouldn't affect others using WAT itself (and if it does, it is more a godot issue than a WAT issue)

**Comment by CodeDarigan** [comment]
Everything should be working fine now.

**Comment by paulhocker** [comment]
I have tested the latest branch in both 3.1 and 3.2RC2 with good results.

I used both a very simple test, and also a more complicated test with some of my own classes/tests with success.

I had to test each one separately because i could not select my test folder from the dropdown. I think this is still an existing bug that I reported already.

**Comment by paulhocker** [comment]
i think this can be closed now
