### ISSUE TITLE
Replace Run Dropdown Menu with Buttons (Enhancement)

### ISSUE THREAD

**Issue by paulhocker** [CodeDarigan/WAT#75]
I find myself wanting a Play All Button for my Tests. It would be great if the three Run items could be on their own button toolbar to make testing a little faster.

**Comment by CodeDarigan** [comment]
The dropdown menu itself was a configuration improvement over buttons.

How would you feel about a key shortcut instead? Like CTRL-R to run all tests?

**Comment by paulhocker** [comment]
sure, i think that will be fine. did the old buttons take up too much real estate?

**Comment by CodeDarigan** [comment]
I think the current format looks a bit sleeker. In addition the code for them got cleaned up. It may also be easier to add more options to the drop down menu.

**Comment by paulhocker** [comment]
good enough for me -- thanks

**Comment by CodeDarigan** [comment]
Closing this in favor #78
