### ISSUE TITLE
Selecting Test Sub Directory Has No Effect

### ISSUE THREAD

**Issue by paulhocker** [CodeDarigan/WAT#76]
When a root Test directory is specified in the WAT settings, the UI will not allow me to select a specific sub-directory. The are viewable, but cannot be selected, the root directory stays.

![2020-01-25_23-53-15](https://user-images.githubusercontent.com/2214652/73131325-bf172780-3fce-11ea-9ecb-8b7c1cbf5330.gif)

**Comment by CodeDarigan** [comment]
There was a signal updating the directory list every time the screen updated so it would get removed. Fixed in the 4.1 branch itself (but release not updated).

I may have to start doing release candidate programs like Godot itself.

**Comment by paulhocker** [comment]
confirmed that this is now working in the 4.1 branch

**Comment by CodeDarigan** [comment]
Updated the release (seems you can force push a tag so I can just update the reference).
