### ISSUE TITLE
`asserts.fail`

### ISSUE THREAD

**Issue by Beefster09** [CodeDarigan/WAT#89]
It would be nice to have an unconditional fail assertion for unimplemented tests.

**Comment by CodeDarigan** [comment]
Sounds good. I'm think:

// Signature
asserts.fail(message = "Unimplemented Test")

// Use
asserts.fail() or asserts.fail("Test is not implemented because reason x")

**Comment by Beefster09** [comment]
Yep. That's pretty much what I was thinking. Thanks for the consideration!
